import { CSGToData } from '../geometry/CSGToData';
import { Polyhedron } from '../geometry/geometry';

const transformModelVertex = (vertex: number[]): number[] => {
    const [x, y, z] = vertex;
    return [(-1 * x) - 250, (-1 * y) + 100, z];
};

export const serializeKeychainObj = (polyhedron: Polyhedron): string => {
    const data = CSGToData(polyhedron.exportFlipped());
    const vertices = data.vertices.map(transformModelVertex);

    return [
        '# File generated by Keychain Generator',
        '# Toysinbox 3D Printing',
        'g keychain',
        '# Vertices',
        ...vertices.map((vertex) => `v ${vertex[0]} ${vertex[1]} ${vertex[2]} 10.0`),
        '',
        '# Faces',
        ...data.indices.map((face) => `f ${face[0] + 1} ${face[1] + 1} ${face[2] + 1}`),
    ].join('\n');
};
